### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by davidpbrown** [wrnice/rsafe#2]
Without change and running example rsafeclient against TEST9, I get this error detail below.

It seems to be centred on what is ln22 in the example:rsafeclient.rs call to auth::register

> let safe_register_resp = auth::register( appdetails );

and then somewhere below auth.rs: ln133 perhaps the unwrap() on ln160?.. I'm guessing as this is beyond me to solve.. but hoping it can be as it's great and very useful to see the functions put to rust.

```
RUST_BACKTRACE=1 ./rsafeclient 
sending request
request sent
200 Ok
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
stack backtrace:
   1:     0x7f7d5b94cd4f - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x7f7d5b94fbeb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x7f7d5b94f86f - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x7f7d5b9446de - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x7f7d5b94fe31 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x7f7d5b94506a - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x7f7d5b94fdce - rust_begin_unwind
   8:     0x7f7d5b9854ff - core::panicking::panic_fmt::h2d3cc8234dde51b4
   9:     0x7f7d5b9857d8 - core::panicking::panic::heeca72c448510af4
  10:     0x7f7d5b89d92d - _<core..option..Option<T>>::unwrap::h9d0b19fe255e444b
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/macros.rs:21
  11:     0x7f7d5b8892b5 - rsafe::auth::register::hf0d70f792a3f47e7
                        at /home/davidpbrown/SAFE/test/rsafe-master/src/auth.rs:133
  12:     0x7f7d5b8830a9 - rsafeclient::main::h9df48ef848df9f6b
                        at /home/davidpbrown/SAFE/test/rsafe-master/examples/rsafeclient.rs:22
  13:     0x7f7d5b94f4a8 - std::panicking::try::call::hca715a47aa047c49
  14:     0x7f7d5b95744b - __rust_try
  15:     0x7f7d5b9573ee - __rust_maybe_catch_panic
  16:     0x7f7d5b94ef4e - std::rt::lang_start::h162055cb2e4b9fe7
  17:     0x7f7d5b887b49 - main
  18:     0x7f7d5aa01f44 - __libc_start_main
  19:     0x7f7d5b882cb8 - <unknown>
  20:                0x0 - <unknown>

```

**Comment by waynenilsen** [comment]
I was able to reproduce. I think I saw some things about how they change the communication with the launcher, all libs probably need to be updated. Steps for repro:

You have to have libsodium-dev package installed to run.

```
git checkout --depth=1 https://github.com/wrnice/rsafe.git
cd rsafe
cargo run --example rsafeclient
```

**Comment by wrnice** [comment]
Hello, thank you for the report !

Indeed the launcher API changed since I wrote this. This was working until API 0.5 , and unfortunately since that moment I couldn't find the time to update the code - Notably I would have to remove the encryption and b64 encoding, as from now communication is in binary.  Several changes also happened in the API and need to be adressed. Other than that, is is quite possible that a general update would be needed with the various crates that I'm using.

Hopefully I manage to find some time to adress this in the coming month, until then please do feel free to fork this and make it better !

**Comment by davidpbrown** [comment]
Thanks; encouraging that you might get to look at it.
I can't suggest how stable the API is but would hope an update might last a while.
